### PR TITLE
add baccyflap.com to members.json

### PR DESCRIPTION
**Pull request by baccyflap**

### CODE REVIEW

**Comment by whitep4nth3r** [comment]
Welcome to the ring!

**Comment by baccyflap** [comment]
Thank you! I'm now just wondering if there's a way of adding links to my page without the whole widget, I'm experimenting but no luck yet.

**Comment by haideralipunjabi** [comment]
I mostly copied over code from the [widget's index.js file](https://github.com/whitep4nth3r/the-claw-webring-widget/blob/main/src/index.js) and adapted it to Next.js (useState, useEffect, etc).

[Here's the code I wrote](https://github.com/haideralipunjabi/haideralipunjabi.com/blob/main/components/webring.tsx) It can definitely be improved, but it works

**Comment by baccyflap** [comment]
Thanks very much for this, now trying to do it with your code, just to see if I can get it to work at all. In the end I want to work out how to do it without a framework but my JS skills are beyond rusty. Currently at

<script src="https://the-claw-webring-widget.netlify.app/the-claw-webring-widget.mjs" type="module"></script>
<div id="claw"></div>
<script>document.getElementById("claw").innerHTML = `<a href="${d}" style="float:left">← prev</a><a href="https://github.com/whitep4nth3r/the-claw-webring" target="_blank">the claw webring</a> <a class="small" href="${J(i).url}">(random)</a> <a style="float:right" href="${m}">next →</a>`;</script>

to no avail. It would work if it could get the constants from the .mjs file, but it can't for obvious reasons that I'm sure I'll find in some 9 year old SE thread at some point. Always a challenge getting webrings to work just so.

**Comment by haideralipunjabi** [comment]
You might be better off using the [code from the repo](https://github.com/whitep4nth3r/the-claw-webring-widget/blob/main/src/index.js), instead of the compiled code.

**Comment by baccyflap** [comment]
Ditched JavaScript and went for a PHP solution. It's a bit clumsy but it gets the job done. I intend to get the random function to work too, shouldn't be too hard, but for now this'll do.

```
<?
$site = 'baccyflap.com';

$json = 'https://github.com/whitep4nth3r/the-claw-webring/raw/main/data/members.json';
$json = file_get_contents($json);
$members = json_decode($json, true);
$max = count($members) - 1;
$me = 0;

foreach (range(0,$max) as $nr) {if(strpos($members[$nr]['url'], $site) !== false){$me = $nr;}}

if ($me == 0) {$clawprv = $max;} else {$clawprv = $me - 1;}
if ($me == $max) {$clawnxt = 0;} else {$clawnxt = $me + 1;}

echo '<a href="' . ($members[$clawprv]['url']) . '" style="float:left">← prev</a>
<a href="https://github.com/whitep4nth3r/the-claw-webring">the claw webring</a>
<a href="' . ($members[$clawnxt]['url']) . '" style="float:right">next →</a><br>';
?>
```

**Pull request merged**
